export default {
  FACEBOOK_LOGIN_SUCCESS: 'FACEBOOK_LOGIN_SUCCESS',
  FACEBOOK_LOGIN_IS_LOADING: 'FACEBOOK_LOGIN_IS_LOADING',
  FACEBOOK_LOGIN_FAIL: 'FACEBOOK_LOGIN_FAIL',
  FETCH_JOBS: 'FETCH_JOBS',
  FETCH_JOBS_IS_LOADING: 'FETCH_JOBS_IS_LOADING',
  LIKE_JOB: 'LIKE_JOB',
  CLEAR_LIKED_JOBS: 'CLEAR_LIKED_JOBS',
};
